### PR TITLE
Add readonly Wallet page

### LINKED ISSUE #89: Add wallets section
If possible this page will list all the customer payment sources of the Customer

### PR DESCRIPTION
**Pull request by pfferrari**
### What does this PR do?
Add new Wallet page in readonly mode to provide a list of customer saved payment sources. (Closes #89)

Screenshot 2023-02-27 alle 17 37 10

### CODE REVIEW

**Comment by pfferrari** [comment]
@malessani we synked this morning with Bera and defined just one visual refinement in the scope of payment sources infos. So finally I removed `valid until` expiry date label in favour of having always `expires` label also in order detail page. I just pushed a commit in order to manage this change and complete PR's related tasks.

**Review by malessani — CHANGES_REQUESTED** [review]
If I save a stripe credit card, I get a wrong formatted expiration on the order:

Screenshot 2023-03-02 at 18 52 28

**Comment by malessani** [comment]
On the wallet I'm not able to see the last 4 digits and the expiration as on the order payment section, I don't know if it is possible to add those information also on the Wallet section.

Screenshot 2023-03-02 at 18 54 05

**Comment by pfferrari** [comment]
> If I save a stripe credit card, I get a wrong formatted expiration on the order:
> 
> Screenshot 2023-03-02 at 18 52 28

I fixed this! The fix is just visible on stg..

**Review by malessani — CHANGES_REQUESTED** [review]
Here a list of things to check and maybe adjust:

- Remove hover on cards
- Align address styles to figma (border in hover)
- Align radius of cards and addresses as in figma (smaller on staging)
- Check font (expires seems to be smaller than in figma)
- Use a white background for cards when in tablet/mobile view

**Comment by pfferrari** [comment]
Some updates here visible in the brand new staging version:

> * Remove hover on cards
done
> * Align address styles to figma (border in hover)
I'll make this adjustment in the addresses dedicated PR in which I'll replace current card with new GridCard component
> * Align radius of cards and addresses as in figma (smaller on staging)
done. it was 0.25rem (4px) and now it is 5px like in Figma
> * Check font (expires seems to be smaller than in figma)
done. I fixed expires size. I wrongly set it to 13px. Now thanks to the addition of `antialiased` classname the font is also shown correctly. We will have to apply antialiased classname to all the application body to align all weights to Figma. => I'll create a dedicated Issue and a future PR
> * Use a white background for cards when in tablet/mobile view
done. it is set always to `bg-white` in GridCard thanks to the fact that in desktop we have a white bg of right column

**Pull request merged**
